/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoResizeInput: typeof import('./src/components/atoms/AutoResizeInput.vue')['default']
    Button: typeof import('./src/components/atoms/Button.vue')['default']
    ChatGemini: typeof import('./src/components/ChatGemini.vue')['default']
    ChatInput: typeof import('./src/components/molecules/ChatInput.vue')['default']
    ChatList: typeof import('./src/components/molecules/ChatList.vue')['default']
    ChatMessage: typeof import('./src/components/atoms/ChatMessage.vue')['default']
    ChatMessage2: typeof import('./src/components/ChatMessage2.vue')['default']
    ChatMessagesList: typeof import('./src/components/molecules/ChatMessagesList.vue')['default']
    ChatPanel: typeof import('./src/components/organisms/ChatPanel.vue')['default']
    copy: typeof import('./src/components/ChatMessage copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MarkdownRenderer: typeof import('./src/components/atoms/MarkdownRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThinkingIndicator: typeof import('./src/components/molecules/ThinkingIndicator.vue')['default']
    TopicList: typeof import('./src/components/molecules/TopicList.vue')['default']
    TopicPanel: typeof import('./src/components/organisms/TopicPanel.vue')['default']
    TypingIndicator: typeof import('./src/components/TypingIndicator.vue')['default']
  }
}
