services:
  postgres:
    image: postgres:latest
    container_name: postgres_challenge_comerc
    env_file: ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:latest
    container_name: redis_challenge_comerc
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    restart: unless-stopped
    env_file: ./backend/.env
    command: redis-server --requirepass "6798"
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '6798', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_challenge_comerc
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: ./backend/.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      REDIS_URL: ${REDIS_URL}
      GEMINI_API_URL: ${GEMINI_API_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_challenge_comerc
    ports:
      - '3001:3001'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
  redisdata:
