### Chat Gemini - Teste do endpoint de chat

@baseUrl = http://localhost:3000

POST {{baseUrl}}/api/chat
Content-Type: application/json

{
  "content": "Qual o meu nome ?",
  "sessionId": "1234abcd"
}

###
POST {{baseUrl}}/api/analyze
Content-Type: application/json

{
  "projectPath": "/app"
}

