FROM oven/bun:1 as base
WORKDIR /usr/src/app

COPY package.json bun.lockb ./
RUN bun install --production --frozen-lockfile

FROM oven/bun:1-slim as production

ENV NODE_ENV=production
WORKDIR /usr/src/app

COPY --from=base /usr/src/app/node_modules ./node_modules

COPY . .

EXPOSE 3000

CMD ["bun", "run", "start"]